<?php

namespace ChatBundle\Repository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindChannels($user)
    {
        return $this->createQueryBuilder('channel_repository')
            ->select('channel_repository')
            ->join('channel_repository.users','contact')
            ->where('contact = :cont')
            ->setParameter('cont', $user)

            ->getQuery()->getResult();
    }
}
