<?php

namespace ChatBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindconctact($contact, $userconnected)
    {
        return $this->createQueryBuilder("c")
            ->select('c')
            ->where(':profilone MEMBER OF c.users')
            ->andwhere(':profiltwo MEMBER OF c.users')
            ->setParameters(array(
           'profilone' => $contact,
           'profiltwo' => $userconnected))
            ->getQuery()->getResult();
    }

}
