<?php

namespace ChatBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindmessages($exist)
    {
        return $this->createQueryBuilder("m")
            ->select('m')
            ->join('m.contact','contact')
            ->where('contact = :cont')
            ->setParameter('cont', $exist)

            ->getQuery()->getResult();
    }

}
