chat:
    path:     /home
    defaults: { _controller: ChatBundle:Chat:chat }


chat_message_add:
    path:     /
    defaults: { _controller: ChatBundle:Chat:Chatadd}
    methods: [GET, POST]


chat_homepage:
    path:     /
    defaults: { _controller: ChatBundle:Default:index }
