chat:
    path:     /home
    defaults: { _controller: ChatBundle:Chat:chat }


chat_message_add:
    path:     /
    defaults: { _controller: ChatBundle:Chat:Chatadd}
    methods: [GET, POST]


chat_homepage:
    path:     /
    defaults: { _controller: ChatBundle:Default:index }

chat_add_chat:
    path: /chatAdd/{id}
    defaults: { _controller: ChatBundle:Chat:addContact}

chat_add_message_chat:
    path: /chatMessage/{contact}/{userconnected}
    defaults: { _controller: ChatBundle:Chat:chatAddMessage}