ChatBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: ChatBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    manyToMany:
        users:
            targetEntity: ChatBundle\Entity\User
            inversedBy: contacts


    oneToMany:
        messages:
            targetEntity: ChatBundle\Entity\Message
            mappedBy: contact