ChatBundle\Entity\Groupe:
    type: entity
    table: null
    repositoryClass: ChatBundle\Repository\GroupeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }


    manyToMany:
        users:
            targetEntity: ChatBundle\Entity\User
            inversedBy: groupes
