ChatBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: ChatBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: 255
        dateTime:
            type: datetime



    manyToOne:
        user:
            targetEntity: ChatBundle\Entity\User
            inversedBy: messages

        contact:
            targetEntity: ChatBundle\Entity\Contact
            inversedBy: messages
        channel:
            targetEntity: ChatBundle\Entity\Channel
            inversedBy: messages
