ChatBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        messages:
            targetEntity: ChatBundle\Entity\Message
            mappedBy: user

    manyToMany:
        contacts:
            targetEntity: ChatBundle\Entity\Contact
            mappedBy: users



        channels:
            targetEntity: ChatBundle\Entity\Channel
            mappedBy: users

